name: Makefile CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: install qemu
      uses: docker/setup-qemu-action@v3
      
    - name: install docker buildx
      uses: docker/setup-buildx-action@v1

    - name: autoreconf
      run: autoreconf --install
    
    - name: configure
      run: ./configure --disable-dependency-tracking

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-12 libcurl4-openssl-dev

    - name: Set GCC and G++ versions
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 60
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 60

    - name: make
      run: make clean && autoreconf && ./configure && make


    - name: run server in background
      run: |
        ./trig_program &  # Run the server in the background
        sleep 5           # Wait for a few seconds to ensure the server is running

    - name: autotest
      run: cd ./tests && make check

    - name: build ls
      run: docker buildx ls 
      
    - name: Login into Docker
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_TOKEN}}

    - name: Job Build Dockerfile image
      run: docker build --platform=linux/amd64 -t korniykom/alpinehttpserver --push .

