name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: autoreconf
      run: autoreconf --install
    
    - name: configure
      run: ./configure --disable-dependency-tracking

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++-12 libcurl4-openssl-dev

    - name: Set GCC and G++ versions
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 60
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 60

    - name: make
      run: make clean && autoreconf && ./configure && make


    - name: run server in background
      run: |
        ./trig_program &  # Run the server in the background
        sleep 5           # Wait for a few seconds to ensure the server is running

    - name: autotest
      run: cd ./tests && make check

    - name: make tarball
      run: make dist

    - name: make deb package
      run: make deb && dpkg --build deb
