name: Makefile CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: autoreconf
      run: autoreconf --install
    
    - name: configure
      run: ./configure --disable-dependency-tracking

    - name: Install dependencies
      run: make

    - name: make tarball
      run: make dist
      
    - name: make deb package
      run: make deb && dpkg --build deb

    - name: run server in background
      run: |
        ./trig_program &  # Run the server in the background
        sleep 5           # Wait for a few seconds to ensure the server is running

    - name: autotest
      run: cd ./tests && make check

    - name: build ls
      run: docker buildx ls 
      
    - name: Login into Docker
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_TOKEN}}

    - name: Job Build Dockerfile image
      run: docker build --platform=linux/amd64 -t korniykom/alpinehttpserver --push .

